export const API_FETCH = {
  TASKS: {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    LOADING: "LOADING",
    DELETE: "DELETE",
    SEARCH: "SEARCH",
    SORT_PRIORITY: "SORT_PRIORITY",
    SORT_DEADLINE: "SORT_DEADLINE",
    SORT_CREATION: "SORT_CREATION",
  },
  USER : {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    LOADING: "LOADING",
    DELETE: "DELETE",
  }
};
